export const SET_ACTIVE_VERTICAL = 'SET_ACTIVE_VERTICAL';
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY';
export const REMOVE_ACTIVE_CATEGORY = 'REMOVE_ACTIVE_CATEGORY';
export const SET_ALL = 'SET_ALL';



